### ISSUE TITLE
MCD is much smaller than original paper?

### ISSUE THREAD

**Issue by Lukelluke** [SamuelBroughton/Mel-Cepstral-Distortion#1]
HI, I observed that the mcd the implement calculate is much small than original paper show, ur mcd is 4.+, however original paper show MCD is 6.+.

Does this ok? Can the result write into paper? 

Hoping for ur answer, thank you!

**Comment by shackysureshot** [comment]
Hi @Lukelluke, yes currently I have been unable to match the papers reported MCD of around 6-7 dB. In addition to using the mcd pip package I have tried using librosa for dynamic time warping and then calculation of MCD. However, the results are again different and not in the authors range of 6-7dB.

**Comment by Lukelluke** [comment]
> Hi @Lukelluke, yes currently I have been unable to match the papers reported MCD of around 6-7 dB. In addition to using the mcd pip package I have tried using librosa for dynamic time warping and then calculation of MCD. However, the results are again different and not in the authors range of 6-7dB.

Yeah! I found this serious problems for months and not find a proper way to solve. But now I need the correct number of MCD for writing paper, it becomes urgently.

1. In most advanced papers' figures, not yet seen any mcd figure less than 5. So the way we use must be improved.
2. I noticed the source implement of MCD :https://github.com/MattShannon/mcd   's MCD score is around 5.2~5.8, at least sensible than us .
3. His files are generated from Merlin implement:https://github.com/CSTR-Edinburgh/merlin ,mainly use .mgc files for calculation. I still wonder whether it's result from the format of files.
4. I also test another implement: https://github.com/ttslr/python-MCD ,whose code used the PYSPTK to calculate gcm. There i countered other problems when i use my own .wav files. Not to mention this , more funny is that the MCD calculated is 2.+, must be wrong(MCD=[4,8])

5. Beside up, i reviewed paper “Mel-cepstral distance measure for objective speech quality assessment”, no more useful information.


Maybe we still need make effort to find the right way of using MCD implement. sigh...

**Comment by Lukelluke** [comment]
Did u noticed the differences between 'get_mcd_plain' and 'get_mcd_dtw' ? i'm confused how to change ur code error.py that can use another of calculate MCD 'in plain'. Hope for ur help!

**Comment by shackysureshot** [comment]
Yes, I have seen those other repositories and have also wondered about the .mgc files. During my time experimenting with different packages I got a huge range of results but never 6-7dB. I'm not sure at which stage the problem is occuring.

In the voice conversion I was doing the speech samples were not aligned so I believe you need dtw?

**Comment by Lukelluke** [comment]
Ok, I review original paper of MCD"MEL CEPSTRAL DISTANCE MEASURE FOR OBJECTIVE SPEECH QUALITY ASSESSMENT" again.

· I'm not sure whether the MCD package(https://github.com/MattShannon/mcd) coding way is totally the same as original paper mentioned.

U can look at dtw.dtw(source,target,logfun) function, it's calculating way is not appeared in original (paper)[https://blog-1301959139.cos.ap-beijing.myqcloud.com/2020/%E5%8D%9A%E5%AE%A2/Mel-cepstral%20distance%20measure%20for%20objective%20speech%20quality%20assessment.pdf]:

![image](https://user-images.githubusercontent.com/10866914/87687357-38dae180-c7b8-11ea-8db1-bbc17e22ce4d.png)
![image](https://user-images.githubusercontent.com/10866914/87687387-4001ef80-c7b8-11ea-80ed-7a34e9f32cbd.png)

Maybe this function shoud be improved.

· secondly， i found that we use the coded 36dim sp, can almost the same as mecps as original paper mentioned features, may it not the main reason for wrong mcd figure.

· 🌟Last but not least, I would prefer to search for MATLAB way of calculating the cep distance. Due to the late night,  i will do search job tomorrow. 
Because there must be more old but useful toolkit in signal field in MATLAB, just as STRAIGHT toolkit( though i still not figure out how to use 'straight')...
Good luck to us


BTW, where can i read ur paper that submit to interspeech 2020. Hoping to read it !

**Comment by Lukelluke** [comment]
maybe we can lookup merlin project, which can produce .mgc / .lf0 / .bap three type files. For my poor coding ability, can not figure out how to use it to convert .wav to those three files quickly. Let's work together! 

https://github.com/CSTR-Edinburgh/merlin

https://github.com/CSTR-Edinburgh/merlin/issues/14

**Comment by Lukelluke** [comment]
> Yes, I have seen those other repositories and have also wondered about the .mgc files. During my time experimenting with different packages I got a huge range of results but never 6-7dB. I'm not sure at which stage the problem is occuring.
> 
> In the voice conversion I was doing the speech samples were not aligned so I believe you need dtw?

Hello！Significant progress！
I use merlin toolkit, successfully convert .wav to those three type of files, however, when i move your two .mgc files into original MCD package, there occure new error:
![image](https://user-images.githubusercontent.com/10866914/87791515-f9be9600-c874-11ea-9d91-ca7bef08fb02.png)

`
(base) huangshengjie@MacBook-Pro mcd % cat test_data/corpus.lst | xargs get_mcd_dtw test_data/ref-examples test_data/synth-examples
processing 2
Traceback (most recent call last):
  File "/Users/huangshengjie/opt/anaconda3/bin/get_mcd_dtw", line 88, in <module>
    main(sys.argv)
  File "/Users/huangshengjie/opt/anaconda3/bin/get_mcd_dtw", line 73, in main
    nat = getNatVecSeq(uttId)
  File "/Users/huangshengjie/opt/anaconda3/lib/python3.7/site-packages/htk_io/base.py", line 109, in __call__
    obj = self.io.readFile(objFile)
  File "/Users/huangshengjie/opt/anaconda3/lib/python3.7/site-packages/htk_io/vecseq.py", line 30, in readFile
    (-1, self.vecSize)
  File "/Users/huangshengjie/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/huangshengjie/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 38100 into shape (40)
`
i don know where the problem is.

another thing, i measured original gcm individually, one MCD is 5.883106 (1254 frames),another is 6.175330 (641 frames),so i think it's reasonable.

***

Let me retell the process i convert .wav to other three files with meilin:
1. install as merlin project readme.
2.cd into tools files, and install as new readme files.
3.cd into SPTK files, install as new readme in this folder
4.cd into egs/voice_conversion/s1/, and do as readme file taught, just do step 1 and step 2. In step one, you can just creat new speakerA / speakerB files, and add our own .wav files. Then do the 2_xxx.sh command than it appear the three pattern files: .mgc / .lf0 / .bap.

Hope for ur assistance to overcome MCD problem!  

***
i already locate the source problem:

![image](https://user-images.githubusercontent.com/10866914/87846212-d2150f80-c900-11ea-9440-9809a4c6fa7b.png)

puzzled with this parameter: --param_order

whatever i change this number, always return different reshape  error, when change to 10, overall MCD = 3.580382 (3810 frames), is too small definitely.

**Comment by wjassim** [comment]
> HI, I observed that the mcd the implement calculate is much small than original paper show, ur mcd is 4.+, however original paper show MCD is 6.+.
> 
> Does this ok? Can the result write into paper?
> 
> Hoping for ur answer, thank you!

Any link for that original paper?
